require(Matrix)

#' kmerdistance package
#'
#' R package use for calculating pairwise distance between genomes base on kmer stratege
#'
#' @docType package
#' @name kmerDistance
NULL

#########################################
##			 Boolean analysis          ##
#########################################
#' calculating pairwise distance between genomes base on kmer stratege
#' 
#' Returns a pairwise distance matrix.
#' 
#' This function compute pairwise distnace of kmer data by using XOR discrete funtion.
#' 
#' @param kmer.length		length of kmer.
#' @param path.to.data		path to test data which are integer kc files generated by using Kanalyze. Default to '../data/' folder.
#' 
#' @return a matrix
#' 
#' @export

kmerDistance.dif <- function(kmer.length,path.to.data="../data"){
	if (is.null(kmer.length))
		stop("Please specify the length of kmer")
	if (is.null(path.to.data))
		stop("Please specify the path to test data")
	
	#read in all kc files in path.to.data
	kcFiles=list.files(path.to.data,"*.kc")
	l=length(kcFiles)
	klist=NULL
    if(l==0)
        stop("No kc files in the data folder: ",path.to.data)
	for (i in 1:l){
        f = file(paste(path.to.data,kcFiles[i],sep="/"))
		temp=read.table(f)
		klist[[i]]=temp[,1]
	}
	#create a matrix to hold the diferential occupancy distance
	dif.occupancy=matrix(0,l,l)
	#calculate the pairwise distance
	for(i in 1:l){
		j=i+1
		while(j <=l){
			l1=length(klist[[i]])
			l2=length(klist[[j]])
			dt=length(intersect(klist[[i]],klist[[j]]))
			dif.occupancy[i,j]=dif.occupancy[j,i]=(l1+l2-2*dt)/(4^kmer.length)		
			j=j+1
		}
	}
	#output result
	difd=data.frame(dif.occupancy)
	names(difd)=kcFiles
	return(difd)
}


#########################################
##			  Linear Algebra           ##
#########################################
#' calculating pairwise distance between genome base on kmer stratege
#' 
#' Returns a pairwise distance matrix.
#' 
#' This function compute pairwise distnace of kmer data by using hierarchical PCA.
#' 
#' @param kmer.length		length of kmer.
#' @param path.to.data		path to test data. Test data are integer kc files generated by using Kanalyze. Default to '../data/' folder
#' @param ifscale			scale flag. if this flag is set to true, the data is scaled.
#' @param ifbinary			binary flag. if this flag is set true, the kmer counts are set to binary number.
#' @param numofp			number of components used to calculate the distance.
#' @param ifplot			plot flag. if this flag is set to true, and numofp is equal to 3, a 3d plot will be generate base on the main components.
#' @param plotmain			The main title (on top) using font and size (character expansion) par("font.main") and color par("col.main").
#' 
#' @return a matrix
#' 
#' @export

kmerDistance.hpca <- function(kmer.length, path.to.data="../data", ifscale = TRUE, ifbinary = FALSE, numofp = 3, ifplot = FALSE, plotmain = "Main"){
	if (is.null(kmer.length))
		stop("Please specify the length of kmer")
	if (is.null(path.to.data))
		stop("Please specify the input file")
	
	#read in all kc files in path.to.data
	kcFiles=list.files(path.to.data,"*.kc")
	l=length(kcFiles)
    if(l==0)
        stop("No kc files in the data folder: ",path.to.data)

	for (i in 1:l){
        f = file(paste(path.to.data,kcFiles[i],sep="/"))
		temp=read.table(f)
		tl=dim(temp)[1]
		if(i==1){
			klist=as.vector(sparseMatrix(c((temp[,1]+1),4^ kmer.length), as.vector(rep(1,tl+1)), x=c(temp[,2],0)))
		} else {
			klist=cbind(klist,as.vector(sparseMatrix(c((temp[,1]+1),4^ kmer.length), as.vector(rep(1,tl+1)), x=c(temp[,2],0))))
		}	
	}
	#scale the data when ifscale flag is on 
	if(ifscale)
		klist=scale(klist)
	if(!ifbinary){
		pcaloadings=princomp(klist)$loadings[,1:numofp]
	} else {
		scaled_binaried = ifelse(klist>0, 1, 0)
		pcaloadings=princomp(scaled_binaried)$loadings[,1:numofp]
	}
	#print 3d structre only when ifplot flag is on and 3 components are used
	if(ifplot && numofp == 3){
		require(rgl,quietly=T)
		thisplot = plot3d(pcaloadings,type="p",col="red",main=plotmain)+text3d(pcaloadings,text=rownames(pcaloadings),font=3,col="blue")
	}
	#output the pairwise distance base on pca result
	thisdist = as.matrix(dist(pcaloadings))
	hpcad=data.frame(thisdist,row.names = NULL,check.rows = FALSE)
	names(hpcad)=kcFiles
	return(hpcad)
}
